server:
  port: 7000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: order-management-service

  datasource:
    url: jdbc:mysql://localhost:3306/aftas?createDatabaseIfNotExist=true
    username: aftas
    password: aftas
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
